### ISSUE TITLE
python3 gbk

### ISSUE THREAD

**Issue by smallevilbeast** [smallevilbeast/ticket#4]
E:\project\ticket\src>python main.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python33\lib\threading.py", line 901, in _bootstrap_inner
    self.run()
  File "C:\Python33\lib\threading.py", line 858, in run
    self._target(_self._args, *_self._kwargs)
  File "E:\project\ticket\src\db\models.py", line 199, in init_db
    _init_common_db()
  File "E:\project\ticket\src\db\models.py", line 152, in _init_common_db
    insert_station_data()
  File "E:\project\ticket\src\db\models.py", line 134, in insert_station_data
    content = fp.read().decode("utf-8").strip("\n")
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 1323: illegal
 multibyte sequence

**Comment by smallevilbeast** [comment]
content = str(fp.read(), 'utf-8').strip("\n")
